/* =============================================================
   ui/elements.js — every DOM reference used by the UI layer.
   ============================================================= */

export const $ = (id) => document.getElementById(id);

export const el = {
  body: document.body,

  // Header / clock
  liveClock: $('liveClock'),
  liveDate: $('liveDate'),
  dailyStatusValue: $('dailyStatusValue'),
  weeklyStatusValue: $('weeklyStatusValue'),
  langFaBtn: $('langFaBtn'),
  langEnBtn: $('langEnBtn'),
  themeToggle: $('themeToggle'),
  fullscreenToggle: $('fullscreenToggle'),
  settingsToggle: $('settingsToggle'),
  toast: $('toast'),
  toastText: $('toastText'),

  // Timer
  modeLabel: $('modeLabel'),
  statusLabel: $('statusLabel'),
  timeDisplay: $('timeDisplay'),
  timeCaption: $('timeCaption'),
  ringSubject: $('ringSubject'),
  elapsedValue: $('elapsedValue'),
  remainingValue: $('remainingValue'),
  progressLabel: $('progressLabel'),
  progressPercent: $('progressPercent'),
  sessionProgressFill: $('sessionProgressFill'),
  primaryBtn: $('primaryBtn'),
  primaryBtnLabel: $('primaryBtnLabel'),
  resetBtn: $('resetBtn'),
  finishBtn: $('finishBtn'),
  breakBtn: $('breakBtn'),

  // Pickers
  kindGrid: $('kindGrid'),
  subjectGrid: $('subjectGrid'),
  presetGroup: document.querySelector('.preset-grid'),
  customDuration: $('customDuration'),
  customMinutes: $('customMinutes'),
  windowStart: $('windowStart'),
  windowEnd: $('windowEnd'),
  applyWindowBtn: $('applyWindowBtn'),

  // Today stats
  todayDate: $('todayDate'),
  todayStudyTime: $('todayStudyTime'),
  todaySessions: $('todaySessions'),
  todayRemainingGoal: $('todayRemainingGoal'),
  dailyGoalValue: $('dailyGoalValue'),
  goalProgressFill: $('dailyGoalProgressFill'),
  subjectBreakdown: $('subjectBreakdown'),
  subjectBreakdownEmpty: $('subjectBreakdownEmpty'),
  timeline: $('timeline'),
  timelineEmpty: $('timelineEmpty'),
  historyList: $('history'),
  historyEmpty: $('historyEmpty'),

  // Exam progress
  examDaysLeft: $('examDaysLeft'),
  examWeekLabel: $('examWeekLabel'),
  examProgressFill: $('examProgressFill'),
  examDaysPassed: $('examDaysPassed'),
  examDaysLeftMini: $('examDaysLeftMini'),
  examEmptyNote: $('examEmptyNote'),

  // Days heatmap
  daysStrip: $('daysStrip'),

  // Weekly plan
  weeklyPlanSaveStatus: $('weeklyPlanSaveStatus'),
  weeklyPlanSaveStatusText: $('weeklyPlanSaveStatusText'),
  weeklyPlanMeta: $('weeklyPlanMeta'),
  weeklyPlanWeekLabel: $('weeklyPlanWeekLabel'),
  weeklyPlanGoal: $('weeklyPlanGoal'),
  weeklyPlanDays: $('weeklyPlanDays'),
  weeklyPlanEmpty: $('weeklyPlanEmpty'),
  weeklyPlanConnectFileBtn: $('weeklyPlanConnectFileBtn'),
  weeklyPlanOpenFileBtn: $('weeklyPlanOpenFileBtn'),
  weeklyPlanSaveNowBtn: $('weeklyPlanSaveNowBtn'),
  weeklyPlanExportBtn: $('weeklyPlanExportBtn'),
  weeklyPlanImportFileInput: $('weeklyPlanImportFileInput'),
  backupDirConnectBtn: $('backupDirConnectBtn'),
  weeklyBackupDirConnectBtn: $('weeklyBackupDirConnectBtn'),
  weeklyBackupStatusText: $('weeklyBackupStatusText'),

  // Save status (main file)
  saveStatus: $('saveStatus'),
  saveStatusText: $('saveStatusText'),

  // Settings modal
  settingsModal: $('settingsModal'),
  settingsCloseBtn: $('settingsCloseBtn'),
  saveSettingsBtn: $('saveSettingsBtn'),
  settingGoalHours: $('settingGoalHours'),
  settingDefaultMinutes: $('settingDefaultMinutes'),
  settingSound: $('settingSound'),
  settingClock24: $('settingClock24'),
  settingReducedMotion: $('settingReducedMotion'),
  settingAutoStart: $('settingAutoStart'),
  studyStartDate: $('studyStartDate'),
  examDate: $('examDate'),
  totalWeeks: $('totalWeeks'),
  newSubjectInput: $('newSubjectInput'),
  addSubjectBtn: $('addSubjectBtn'),
  subjectManageList: $('subjectManageList'),
  connectFileBtn: $('connectFileBtn'),
  openFileBtn: $('openFileBtn'),
  saveNowBtn: $('saveNowBtn'),
  exportBtn: $('exportBtn'),
  importFileInput: $('importFileInput'),
  clearDataBtn: $('clearDataBtn'),

  // Post-session modal (topic picker + test analysis)
  analysisModal: $('analysisModal'),
  analysisModalTitleEl: $('analysisModalTitle'),
  analysisModalSubtitleEl: $('analysisModalSubtitle'),
  analysisCloseBtn: $('analysisCloseBtn'),
  analysisSubjectLabel: $('analysisSubjectLabel'),
  analysisTopic: $('analysisTopic'),
  analysisTopicOptions: $('analysisTopicOptions'),
  analysisMetricsSection: $('analysisMetricsSection'),
  analysisTestCount: $('analysisTestCount'),
  analysisCorrectPercent: $('analysisCorrectPercent'),
  analysisErrorCount: $('analysisErrorCount'),
  analysisSaveBtn: $('analysisSaveBtn'),
  analysisSkipBtn: $('analysisSkipBtn'),

  // Daily check-in modal
  checkinModal: $('checkinModal'),
  checkinCloseBtn: $('checkinCloseBtn'),
  checkinSaveBtn: $('checkinSaveBtn'),
  checkinSkipBtn: $('checkinSkipBtn'),
  checkinBedTime: $('checkinBedTime'),
  checkinWakeTime: $('checkinWakeTime'),
  checkinSleepHours: $('checkinSleepHours'),
  checkinSleepQuality: $('checkinSleepQuality'),
  checkinSleepQualityValue: $('checkinSleepQualityValue'),
  checkinRoutineDone: $('checkinRoutineDone'),
  checkinRoutineStepsWrap: $('checkinRoutineStepsWrap'),
  checkinRoutineSteps: $('checkinRoutineSteps'),
  checkinActivity1: $('checkinActivity1'),
  checkinOperation1: $('checkinOperation1'),
  checkinYesterdayQuality: $('checkinYesterdayQuality'),
  checkinYesterdayQualityValue: $('checkinYesterdayQualityValue'),
  checkinExerciseDone: $('checkinExerciseDone'),
  checkinExerciseMinutesWrap: $('checkinExerciseMinutesWrap'),
  checkinExerciseMinutes: $('checkinExerciseMinutes'),
  checkinConnectFileBtn: $('checkinConnectFileBtn'),
  checkinOpenFileBtn: $('checkinOpenFileBtn'),
  checkinSaveNowBtn: $('checkinSaveNowBtn'),
  checkinExportBtn: $('checkinExportBtn'),
  checkinImportFileInput: $('checkinImportFileInput'),
  checkinBackupDirConnectBtn: $('checkinBackupDirConnectBtn'),
  checkinBackupStatusText: $('checkinBackupStatusText'),
  checkinSaveStatus: $('checkinSaveStatus'),
  checkinSaveStatusText: $('checkinSaveStatusText'),
};
